Getting Started
---------------

This part of the documentation focuses on explaining Bungeni, setting up your Python environment. It then proceeds with instructions on how to get Bungeni running seamlessly on the Plone CMS. Instructions on how to make server updates using tools like capistrano are included.

.. toctree::
   :maxdepth: 2

   starting/which-python

- Properly Install Python

 .. toctree::
    :maxdepth: 1

    starting/install/osx
    starting/install/win
    starting/install/linux

- Properly Install Plone

 .. toctree::
    :maxdepth: 1
    
    starting/install/plone

		
- System Administration

 .. toctree::
    :maxdepth: 1

    starting/sysadmin/systemsadmin

Installing Bungeni
------------------

.. toctree::
   :maxdepth: 2

   bungeni/about
   writing/style
   writing/documentation
   writing/tests
   writing/license


Customizing Bungeni and Writing Awesome Code
--------------------------------------------

This part of the guide focuses on best practices for writing Python code.

.. toctree::
   :maxdepth: 2

   writing/structure
   writing/style
   writing/documentation
   writing/tests
   writing/license



Scenario Guide
--------------

This part of the guide focuses on tool and module advice based on
different scenarios.

.. toctree::
   :maxdepth: 2

   scenarios/client
   scenarios/web
   scenarios/cli
   scenarios/gui
   scenarios/db
   scenarios/admin
   scenarios/ci
   scenarios/speed
   scenarios/scientific


Shipping Great Code
-------------------

This part of the guide focuses on deploying your Python code.

.. toctree::
   :maxdepth: 2

   shipping/packaging
   shipping/freezing


Development Environment
-----------------------

.. toctree::
   :maxdepth: 2

   dev/env
   dev/virtualenvs




Additional Notes
----------------

This part of the guide, which is mostly prose, begins with some
background information about Python, then focuses on next steps.

.. toctree::
   :maxdepth: 2

   intro/duction
   intro/community
   intro/learning
   intro/documentation
   intro/news




--------------------------------------

Contibution notes and legal information are here (for those interested).

.. toctree::
   :maxdepth: 2

   notes/contribute
   notes/license
   notes/styleguide





