Getting Started
---------------

This part of the documentation focuses on explaining Bungeni, setting up your Python environment. It then proceeds with instructions on how to get Bungeni running seamlessly on the Plone CMS. Instructions on how to make server updates using tools like capistrano are included.

.. toctree::
   :maxdepth: 2

   starting/which-python

- Properly Install Python

 .. toctree::
    :maxdepth: 1

    starting/install/osx
    starting/install/win
    starting/install/linux

- Properly Install Plone

 .. toctree::
    :maxdepth: 1
    
    starting/install/plone

Installing Bungeni
------------------

.. toctree::
   :maxdepth: 2

   bungeni/about
   bungeni/bungeni
   bungeni/bungeni_help
   bungen/contrib


Architecture
------------

.. toctree::
   :maxdepth: 2

   bungeni/arch_overview


Systems Administration
----------------------

.. toctree::
   :maxdepth: 2

   sysadmin/webserver
   sysadmin/dbserver
   sysadmin/fabdeploy
   sysadmin/capistrano

Customizing Bungeni and Writing Awesome Code
--------------------------------------------

This part of the guide focuses on best practices for writing Python code.

.. toctree::
   :maxdepth: 2

   writing/structure
   writing/style
   writing/documentation
   writing/tests
   writing/license



Development Guide
-----------------

This part of the guide focuses on tool and module advice based on
different scenarios and workflows availed when you use the Bungeni portal.

.. toctree::
   :maxdepth: 2

   development/intro


Development Environment
-----------------------

.. toctree::
   :maxdepth: 2

   dev/env
   dev/virtualenvs




Additional Notes
----------------

This part of the guide, which is mostly prose, begins with some
background information about Python, then focuses on next steps.

.. toctree::
   :maxdepth: 2

   intro/duction
   intro/community
   intro/learning
   intro/documentation
   intro/news




--------------------------------------

Contibution notes and legal information are here (for those interested).

.. toctree::
   :maxdepth: 2

   notes/contribute
   notes/license
   notes/styleguide